version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11 

  build:
    commands:
      - echo Installing dependencies...
      - pip install -r lambda/requirements.txt -t lambda/

      - echo Packaging lambda...
      - cd lambda && zip -r ../lambda.zip .
      - cd ..

artifacts:
  files:
    - lambda.zip
    - template.yml

    